name = "Packwizmods"
author = "Flipper&EyEyron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7479e02e35c7262f4ef724b2868bf8fb9a4e14c7157668c529eb2ca8cf3bd00"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
