name = "Packwizmods"
author = "Flipper&EyEyron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1308c4a29b85fae7cd6d829a87284f799f02f0e8d60a42522359aee17678bff5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
