name = "Packwizmods"
author = "Flipper&EyEyron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53a49bbeec1039803f81656dca5145f56a6467f2bfbf9e94463ef675d2d618cc"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
