name = "Packwizmods"
author = "Flipper&EyEyron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "116fe4667c08362ab4cf59b4545824d7b222bfb233418de73727f9b343fda88e"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
